language: php

sudo: false

env:
  global:
    - COMPOSER_MEMORY_LIMIT="-1"

matrix:
    include:
      - php: 7.2
        env: COMPOSER_ARGS="" WITH_CS="true"
      - php: 7.3
        env: COMPOSER_ARGS=""
      - php: 7.4
        env: COMPOSER_ARGS=""

      - php: 7.2
        env: COMPOSER_ARGS="--prefer-lowest"
      - php: 7.3
        env: COMPOSER_ARGS="--prefer-lowest"
      - php: 7.4
        env: COMPOSER_ARGS="--prefer-lowest"

cache:
    directories:
      - $HOME/.composer/cache

install:
    - IFS=$'\n'; COMMIT_SCA_FILES=($(git diff --name-only --diff-filter=ACMRTUXB "${TRAVIS_COMMIT_RANGE}")); unset IFS

before_script:
    - phpenv config-rm xdebug.ini || true
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
    - bin/phpunit
    - if [[ "$WITH_CS" == "true" ]]; then bin/paysera-php-cs-fixer fix -v --config=.php_cs --dry-run --stop-on-violation --path-mode=intersection "${COMMIT_SCA_FILES[@]}"; fi
